<%@ Page Title="" Language="C#" MasterPageFile="~/admin/site.master" AutoEventWireup="true" CodeFile="ManageCustomer.aspx.cs" Inherits="admin_ManageCustomer" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
    AutoGenerateColumns="False" DataKeyNames="Id" 
    DataSourceID="SqlDataSource1" EnableModelValidation="True" Width="766px" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <AlternatingRowStyle BackColor="#CCCCCC" />
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="Id" 
                InsertVisible="False" ReadOnly="True" SortExpression="Id" />
            <asp:BoundField DataField="membername" HeaderText="membername" 
                SortExpression="membername" />
            <asp:BoundField DataField="address" HeaderText="address" 
                SortExpression="address" />
            <asp:BoundField DataField="city" HeaderText="city" 
                SortExpression="city" />
            
            <asp:BoundField DataField="state" HeaderText="state" 
                SortExpression="state" />
            <asp:BoundField DataField="pincode" HeaderText="pincode" 
                SortExpression="pincode" />
            <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
            <asp:BoundField DataField="mobile" HeaderText="mobile" 
                SortExpression="mobile" />
        </Columns>
        <HeaderStyle BackColor="#999999" Font-Size="Medium" HorizontalAlign="Center" />
        <RowStyle BackColor="Silver" Font-Size="Larger" HorizontalAlign="Center" />
    </asp:GridView>

    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
    ConnectionString="<%$ ConnectionStrings:mycon %>" 
    DeleteCommand="delete from cart where username=@email; delete from orders where orderedby=@email; delete from feedback where username=@email; delete from comments where username=@email; delete from personaldetails where id=@id; delete from logindetails where username=@email;" 
    SelectCommand="SELECT * FROM [personaldetails]" 
    
        UpdateCommand="update personaldetails set membername=@membername,address=@address,city=@city,state=@state,pincode=@pincode,mobile=@mobile where id=@id">
        <DeleteParameters>
            <asp:ControlParameter ControlID="GridView1" Name="@id" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@email" 
                PropertyName="SelectedValue" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="GridView1" Name="@membername" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@address" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@city" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@state" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@pincode" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@mobile" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@id" 
                PropertyName="SelectedValue" />
        </UpdateParameters>
</asp:SqlDataSource>
</asp:Content>

