<%@ Page Title="" Language="C#" MasterPageFile="~/admin/site.master" AutoEventWireup="true" CodeFile="ManageProducts.aspx.cs" Inherits="admin_ManageProducts" %>


<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:mycon %>" DeleteCommand="delete from comments where laptopid=@id;
delete from cart where productid=@id;
delete from laptops where id=@id;" 
        SelectCommand="SELECT [id], [company], [model], [ram], [hdd], [display], [graphiccard], [processor], [audio], [dvdwriter], [wifi], [bluetooth], [webcam], [os], [additional] FROM [laptops] ORDER BY [id] DESC" 
        UpdateCommand="update laptops set company=@company,model=@model,ram=@ram, hdd=@hdd,display=@display,graphiccard=@graphiccard, processor=@processor, audio=@audio, dvdwriter=@dvdwriter, wifi=@wifi, bluetooth=@bluetooth, webcam=@webcam, os=@os, additional=@additional where id=@id">
        <DeleteParameters>
            <asp:ControlParameter ControlID="GridView1" Name="@id" 
                PropertyName="SelectedValue" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="GridView1" Name="@comapny" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@model" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@ram" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@hdd" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@display" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@graphiccard" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@processor" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@audio" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@dvdwriter" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@wifi" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@bluetooth" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@webcam" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@os" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@additional" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@id" 
                PropertyName="SelectedValue" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
        AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" 
        EnableModelValidation="True" Height="213px" Width="951px">
        <AlternatingRowStyle BackColor="#999999" />
        <Columns>
            <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" 
                ReadOnly="True" SortExpression="id" />
            <asp:BoundField DataField="company" HeaderText="company" 
                SortExpression="company" />
            <asp:BoundField DataField="model" HeaderText="model" SortExpression="model" />
            <asp:BoundField DataField="ram" HeaderText="ram" SortExpression="ram" />
            <asp:BoundField DataField="hdd" HeaderText="hdd" SortExpression="hdd" />
            <asp:BoundField DataField="display" HeaderText="display" 
                SortExpression="display" />
            <asp:BoundField DataField="graphiccard" HeaderText="graphiccard" 
                SortExpression="graphiccard" />
            <asp:BoundField DataField="processor" HeaderText="processor" 
                SortExpression="processor" />
            <asp:BoundField DataField="audio" HeaderText="audio" SortExpression="audio" />
            <asp:BoundField DataField="dvdwriter" HeaderText="dvdwriter" 
                SortExpression="dvdwriter" />
            <asp:BoundField DataField="wifi" HeaderText="wifi" SortExpression="wifi" />
            <asp:BoundField DataField="bluetooth" HeaderText="bluetooth" 
                SortExpression="bluetooth" />
            <asp:BoundField DataField="webcam" HeaderText="webcam" 
                SortExpression="webcam" />
            <asp:BoundField DataField="os" HeaderText="os" SortExpression="os" />
            <asp:BoundField DataField="additional" HeaderText="additional" 
                SortExpression="additional" />
        </Columns>
        <HeaderStyle BackColor="#666666" Font-Bold="True" 
            Font-Names="Bookman Old Style" Font-Underline="True" HorizontalAlign="Center" />
        <RowStyle BackColor="#CCCCCC" Font-Names="Berlin Sans FB" 
            HorizontalAlign="Center" VerticalAlign="Middle" />
    </asp:GridView>
    <br />
    <br />

</asp:Content>

