<%@ Page Title="" Language="C#" MasterPageFile="~/admin/site.master" AutoEventWireup="true" CodeFile="ManageNews.aspx.cs" Inherits="admin_ManageNews" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
    AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
    AutoGenerateEditButton="True" DataKeyNames="newsid" 
    DataSourceID="SqlDataSource1" EnableModelValidation="True" Width="820px">
        <AlternatingRowStyle BackColor="#999999" Font-Size="Larger" 
            HorizontalAlign="Center" />
        <Columns>
            <asp:BoundField DataField="newsid" HeaderText="newsid" InsertVisible="False" 
                ReadOnly="True" SortExpression="newsid" />
            <asp:BoundField DataField="newsheading" HeaderText="newsheading" 
                SortExpression="newsheading" />
            <asp:BoundField DataField="newscontent" HeaderText="newscontent" 
                SortExpression="newscontent" />
            <asp:BoundField DataField="postedon" HeaderText="postedon" 
                SortExpression="postedon" />
        </Columns>
        <HeaderStyle BackColor="#333333" Font-Size="Medium" HorizontalAlign="Center" />
        <RowStyle BackColor="#CCCCCC" Font-Size="Larger" HorizontalAlign="Center" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
    ConnectionString="<%$ ConnectionStrings:mycon %>" 
    DeleteCommand="delete from news where NewsId=@newsId" 
    SelectCommand="SELECT * FROM [news]" 
    UpdateCommand="update News set newsheading=@newsHeading, newsContent=@newsContent where NewsId=@newsId">
        <DeleteParameters>
            <asp:ControlParameter ControlID="GridView1" Name="@newsId" 
                PropertyName="SelectedValue" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="GridView1" Name="@newsHeading" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@newsContent" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="@newsId" 
                PropertyName="SelectedValue" />
        </UpdateParameters>
</asp:SqlDataSource>
</asp:Content>

