<%@ Page Title="" Language="C#" MasterPageFile="~/customer/MasterPage.master" AutoEventWireup="true" CodeFile="BuyProduct.aspx.cs" Inherits="customer_BuyProduct" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
        AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" DataSourceID="SqlDataSource1" 
        EnableModelValidation="True" Height="117px" Width="522px">
        <Columns>
            <asp:BoundField DataField="productid" HeaderText="productid" 
                SortExpression="productid" />
            <asp:BoundField DataField="productname" HeaderText="productname" 
                SortExpression="productname" />
            <asp:BoundField DataField="price" HeaderText="price" 
                SortExpression="price" />
            <asp:BoundField DataField="quantity" HeaderText="quantity" 
                SortExpression="quantity" />
        </Columns>
        <RowStyle HorizontalAlign="Center" VerticalAlign="Middle" />
    </asp:GridView>


    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:mycon %>" 
        
        SelectCommand="SELECT [productid], [productname], [price], [quantity] FROM [cart] WHERE ([username] = @username)">
        <SelectParameters>
            <asp:SessionParameter Name="username" SessionField="session" Type="String" />
        </SelectParameters>
    </asp:SqlDataSource>


    <br />
    <asp:Button ID="Button1" runat="server" onclick="Button1_Click" 
        Text="Confirm Order" />
</asp:Content>

